# Copyright (c) Jupyter Development Team.
# Distributed under the terms of the Modified BSD License.
ARG BASE_CONTAINER=jupyter/base-notebook
FROM $BASE_CONTAINER

LABEL maintainer="Jupyter Project <jupyter@googlegroups.com>"


USER $NB_UID

# Install Python 3 packages
RUN conda install -c conda-forge --quiet --yes \
    'matplotlib' \
    'numpy' \
    'pandas' \
    'scikit-learn' \
    'scipy' \
    'sympy' \
    && \
    conda clean --all -f -y 
    
# Generate config file and add password
# RUN jupyter notebook --generate-config
# -> Config file generated by docker stack
RUN echo "c.NotebookApp.password='sha3_256:f6bb3e8067e0:ac4770f841a9209f10d6b5e4c5fdbaf0ce6cceddf45ad6ffe76811f040c5cccb'">>/home/$NB_USER/.jupyter/jupyter_notebook_config.py


# Copy notebook files and python library

ADD --chown=jovyan:users *.ipynb /home/$NB_USER/
ADD --chown=jovyan:users *.py /home/$NB_USER/
RUN jupyter trust /home/$NB_USER/*.ipynb




